
name: List Affected Projects

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  identify-affected:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Cache Turbo Cache
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ hashFiles('**/turbo.json', '**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install Turbo and dependencies
        run: |
          npm install -g turbo
          npm install

      # - name: Fetch develop branch (for comparison)
      #   run: |
      #     # Fetch the develop branch to compare against it
      #     git fetch origin develop
      #     #git checkout develop 
      - name: Get the latest develop branch
        run: |
          git fetch origin develop
          git checkout develop  # Switch to the develop branch to compare
     
      - name: Fetch all branches
        run: git fetch --all    
      - name: Checkout the feature branch again (after develop)
        run: git checkout ${{ github.head_ref || github.ref_name }}
        

      # - name: Identify and print affected projects
      #   run: |
      #       TURBO_SCM_BASE=origin/develop turbo ls --affected
            
      # - name: Build  affected projects
      #   run: |
      #      npm run build 
      - name: List affected projects
        id: list-affected
        run: |
          TURBO_SCM_BASE=origin/develop turbo ls --affected > affected.txt
          cat affected.txt

      - name: Build affected projects
        run: |
          while IFS= read -r line; do
            project_name=$(echo "$line" | awk '{print $1}')
            project_path=$(echo "$line" | awk '{print $2}') 
            #echo "Building project: $project_name at $project_path"  
          done < affected.txt
